import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Skin Laundry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.nicepng.com/maxp/u2w7r5t4y3o0i1q8" />
      </Head>
      <div className="container mt-4">
        <div className="text-center font-bold text-3xl">Home Page</div>
      </div>
    </div>
  );
};



export default Home;
